FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine AS base
WORKDIR /app
EXPOSE 5000

FROM microsoft/dotnet:2.2-sdk-alpine AS build
WORKDIR /src

COPY ./*.sln ./

COPY */*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ${file%.*} && mv $file ${file%.*}; done
RUN dotnet restore

COPY . ./
RUN dotnet build -c Release -o /app

FROM node:10-alpine

WORKDIR /usr/local/sbin

COPY . .

COPY /Web.Site/package*.json /Web.Site/

WORKDIR /Web.Site/

RUN npm install

RUN npm run production

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

ENV ASPNETCORE_Environment=Development
ENV ConnectionStrings:Sendgrid=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
ENV ConnectionStrings:Storage=DefaultEndpointsProtocol=https;AccountName=ricardogaefke;AccountKey=zTy7ziEx+giOIEiYz9a9DQwV1JJVMgxZuj88fWvu8AwCZ5nok3EFJ2k6GzEvSxzPbQoLUhzpyDYqCaR+GcrMzQ==;EndpointSuffix=core.windows.net

ENV ASPNETCORE_URLS="http://*:5000"
ENTRYPOINT ["dotnet", "Web.Site.dll"]